### PR TITLE
Importing Excel tables

### PR DESCRIPTION
**Pull request by marclegeay**
I tested the new Cytoscape 3.8.0-SNAPSHOT and I realized that now Java 11 use the default Locale to read Excel files.

I modified the import so that, if it's an Excel file, the decimal separator is not the default dot, but the locale one.

### CODE REVIEW

**Review by mikekucera — COMMENTED** [review]
The changes to ImportTablePanel look fine. However, I'm concerned about the changes to LoadTableReaderTask because they are not backwards compatible. The command docs for the `decimalSeparator` argument of the `table import file` command explicitly says that the default is the dot. But with your changes that will no longer be true because the default would depend on the user's locale. That could break existing scripts or workbooks that depend on the documented behaviour. For that reason I don't think we can accept the changes to LoadTableReaderTask.

**Comment by marclegeay** [comment]
Thank you for your review.
It made me think and discover some issues.

First, the `decimalSeparator` argument is not working because, apparently, Character are now well handled by commands (it is considered as empty, even if we change its value). I have to admit that I did not test this argument properly, I just tested it on the GUI and with the default value of the command, then assumed it worked -- I was wrong.
I changed the type of `decimalSeparator` from `Character` to `String` and just use the first `char` of the `String`, it's ugly but it works.

Second, the Excel files are handled weirdly. To be honest, a decimal separator should not be used with Excel files since Excel gives the type of each cell, so a numeric cell should be numeric (but we have to identify if its `int`, `long` or `double`.
The problem is that Cytoscape formats the value as a `String` (according to the Locale), and then guesses the type from this `String`.
So if I have a comma-Locale, then 1.5 will be formatted as "1,5" and is analyzed to guess the type which will be String if I use the default `decimalSeparator` '.'.

I think the best would be that:
- `decimalSeparator` should be changed as `String`.
- `decimalSeparator` should be used only for text-files, and the type guessing from Excel files should come from what Excel states.

If you agree with that I will try to modify it and change the pull request.

**Comment by mikekucera** [comment]
Hi, I added proper support for char and Character Tunable fields, so decimalSeparator can stay as type Character now. Thanks for catching that, its a bug that needed to be fixed properly.

I'm not an expert on Excel but what you say about type guessing sounds like a good idea. The only issue is that we are very late in the 3.8 release cycle and we may not be able to accept complex changes that need a lot of testing at this time. Your changes would be appreciated but they may have to go into the 3.8.1 release.

**Comment by marclegeay** [comment]
Hi,

I tested the latest release and indeed the Character tunable is now working well.

I understand that you want to release the 3.8.0 version. I will try to make the changes, test them, and commit them as soon as possible, if it's for the 3.8.1 release... so be it! :)

**Comment by marclegeay** [comment]
Hi,

I tested the modifications on three different OS:
- Ubuntu 16.04 (Danish locale)
- Mac OS X 10.14.16 (Danish locale)
- Windows 10 (French locale)

The types are well identified in all of them.

I think this should be incorporated in Cytoscape 3.8.0 because without this modifications, the Excel files cannot be imported if you have a comma as decimal separator in your locale. Even if you change your locale to use the dot instead of the comma, Java 11 just look at your "default" country locale and do not care about your custom changes.
Meaning that several countries in Europe with a comma as decimal separator won't be able to import Excel files easily.

Best,
Marc.

**Comment by mikekucera** [comment]
Hi Marc,
We would like to merge these changes so they can be part of Cytoscape 3.8 (which is releasing very soon). I would like to give this a test myself first though. Can you please send me an excel file that I can use to test this, ie a file you could not import in 3.7 but can import with your fixes. Thanks!

**Comment by marclegeay** [comment]
Hi,

Here is the file I used for my tests: [test.xlsx](https://github.com/cytoscape/cytoscape-impl/files/4109754/test.xlsx).
The types should be:
Double, String, String, Double, Long, Boolean, Int, Int, String, Double.

This file is imported correctly with Cytoscape 3.7, but not with Cytoscape 3.8 and a "comma locale".
With my modification, it should be imported correctly with Cytoscape 3.8 and all locales.

**Comment by mikekucera** [comment]
I tested the changes on Mac with the French and English locales and it works really well. I think this should be in 3.8 so I have merged the commits. 

The only issue with the changes is that you used spaces instead of tabs, so I'll have to reformat the code. I'll do that in a separate commit.

Thank you for your work.

**Pull request merged**
